apiVersion: v1
kind: Service
metadata:
  name: simple-social-web
  labels:
    name: simple-social-web
    app: simple-social
spec:
  selector:
    name: simple-social-api
    app: simple-social 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
  
 


