apiVersion: v1
kind: Service
metadata:
  name: simple-social-api-service
  labels:
    name: simple-social-api-service
    app: simple-social
spec:
  selector:
    name: simple-social-api
    app: simple-social 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
 


